### PR TITLE
Move to async I/O with Tokio

### PR DESCRIPTION
**Pull request by afilini**

### CODE REVIEW

**Comment by RCasatta** [comment]
ack e1dbfd7ceb612ae9a82d1e5782aa184be5a63f02

**Comment by afilini** [comment]
Do you mean tokio as a dependency? because i don't think it can be removed in any way, unless you implement the logic both in a sync and async way. Currently the main logic is asynchronous, so you'll always need tokio for that, even if the exposed interface is synchronous.

**Comment by RCasatta** [comment]
no I mean tokio as runtime, to use sync methods you still need to run the tokio runtime

**Comment by RCasatta** [comment]
ack dcad619

**Pull request merged**
